services:
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    restart: always
  
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
    restart: always

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-server
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-server:8761/eureka/
    restart: always
  
  authentication-rest:
    build: ./authentication-rest
    deploy:
      replicas: 3
    ports:
      - "8001-8003:8086"
    depends_on:
      - config-server
      - discovery-server
      - api-gateway
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-server:8761/eureka/
    restart: always

  event-management-soap:
    build: ./event-management-soap
    deploy:
      replicas: 3
    ports:
      - "8004-8006:8081"
    depends_on:
      - config-server
      - discovery-server
      - api-gateway
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-server:8761/eureka/
    restart: always

  event-merch-prosumer-rest:
    build: ./event-merch-prosumer-rest
    deploy:
      replicas: 3
    ports:
      - "8007-8009:8083"
    depends_on:
      - config-server
      - discovery-server
      - api-gateway
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-server:8761/eureka/
    restart: always

  feedback-prosumer-rest:
    build: ./feedback-prosumer-rest
    deploy:
      replicas: 3
    ports:
      - "8010-8012:8082"
    depends_on:
      - config-server
      - discovery-server
      - api-gateway
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-server:8761/eureka/
    restart: always

  merchandising-rest:
    build: ./merchandising-rest
    deploy:
      replicas: 3
    ports:
      - "8013-8015:8085"
    depends_on:
      - config-server
      - discovery-server
      - api-gateway
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-server:8761/eureka/
    restart: always

  sales-analysis-prosumer-rest:
    build: ./sales-analysis-prosumer-rest
    deploy:
      replicas: 3
    ports:
      - "8016-8018:8084"
    depends_on:
      - config-server
      - discovery-server
      - api-gateway
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-server:8761/eureka/
    restart: always

  soap-proxy-prosumer-rest:
    build: ./soap-proxy-prosumer-rest
    deploy:
      replicas: 3
    ports:
      - "8019-8021:8087"
    depends_on:
      - config-server
      - discovery-server
      - api-gateway
      - event-management-soap
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-server:8761/eureka/
    restart: always